iterations = 10                # The gloabl amount of iterations (defaults to 200)
max_execution_time = "60s"     # The global time before the process is supposed to get killed (defaults to 10)

[[command]]
cmd = "./rust-fibonacci"       # The cmd to execute
args = ["20000"]

[[command]]
cmd = "./go-fibonacci"
args = ["20000"]
iterations = 3                 # Override the gloabl iteration limit for this cmd
max_execution_time = "300s"    # Override the global max_time for this cmd
